// Invented copy for the columns. Every name, street, firm and event here is fictional.
export const SENT = [
  'The harbour board met on Monday evening and agreed, after some warmth, to defer the question of the pier.',
  'Mr. Tobias Venn, chairman of the board, said that a decision made in haste would be paid for in timber.',
  'Tides at the bar are expected at ten minutes to seven, with a swell from the north-west after midday.',
  'The Misses Pargeter have given forty yards of flannel to the winter fund, and ask that it be cut small.',
  'A brown umbrella, much mended, was left on the ferry steps and may be claimed at the booking office.',
  'The bell ringers of St. Aldric practised until nine, and the neighbours are asked to bear it with patience.',
  'Fish were scarce at the quay on Saturday, and the price of herring rose by a penny the dozen.',
  'The lighthouse will be painted in the spring, weather permitting, and the keeper has promised white.',
  'Pupils of the Clamp Street school will give a recital of songs on Thursday; the doors open at seven.',
  'A gentleman of Seaview Terrace reports that his hens have laid forty-one eggs in a week, a record for the street.',
  'The tram company announces that the last car on the Eastgate line will leave ten minutes earlier.',
  'No fewer than three hundred persons attended the fair, and the vicar reckons the takings at eleven pounds.',
  'The new reading room is open daily, and the librarian asks that boots be wiped at the door.',
  'Several boats were seen to put out before the fog, and all were accounted for by nightfall.',
  'The council surveyor has measured the wall at Gannet Lane and finds it three inches out of true.',
  'A meeting of the fishermen’s friendly society will be held on Wednesday at the Anchor, tea provided.',
  'Mrs. Ottoline Rudge, who kept the draper’s shop for thirty years, was presented with a clock.',
  'The price of coal is unchanged, but merchants warn that a hard frost would alter that at once.',
  'Complaints are again heard of the lamp at the corner of Rope Walk, which has gone out nightly since March.',
  'A dance in aid of the lifeboat will take place in the Assembly Rooms, with music by a quartet from the Bay.',
  'The harbour master reminds skippers that the new channel buoys are red to port and white to starboard.',
  'It is understood that the mill will take on twelve hands before the quarter-day, subject to orders.',
  'Our readers are asked to send any news of lost property, found property, or property of doubtful ownership.',
  'The bakers of the town have agreed to hold the price of the quartern loaf until Michaelmas.',
  'Cricket: the Bay eleven beat the Marsh by four wickets, the winning hit being made in the last over.',
  'A fine specimen of the sunfish was landed at the slip yesterday and may be viewed at the fishmonger’s.',
  'There will be no market on Good Friday, and the stallholders have been notified by the clerk.',
  'The surveyor was heard to say that the pier had stood eighty years and might stand eighty more, with care.',
  'Fog signals were sounded from the point for six hours, to the great comfort of the coasting trade.',
  'Tenders are invited for the supply of lamp oil to the harbour lights for the year ensuing.',
  'The sexton asks that the churchyard gate be kept shut, on account of the goats.',
  'An entertainment was given on Friday for the benefit of the widows’ fund, and was well attended.',
  'It is a matter of general remark that the clock on the town hall has kept better time since it was oiled.',
  'The doctor is of opinion that the damp in Cooper’s Row is due to the drains and not to the weather.',
];
export const HEADS = ['COUNCIL DEFERS PIER VOTE', 'BELL RINGERS REHEARSE', 'HERRING PRICE RISES A PENNY', 'LIFEBOAT DANCE ON FRIDAY', 'LAMP AT ROPE WALK OUT AGAIN', 'LIBRARIAN ASKS FOR CLEAN BOOTS'];
export const ADS = [
  ['OLDHAM & SON', 'Ship Chandlers', 'Rope, tar, lamp oil & canvas', 'Gannet Lane'],
  ['DR. PELLEW’S', 'Sea-Air Tonic', 'For the nerves & the chest', 'One shilling'],
  ['THE ANCHOR', 'Tea & Chops', 'Open from six', 'Quay Steps'],
];
export const TIDES = [['Mon', '6.50', '19.10'], ['Tue', '7.35', '19.55'], ['Wed', '8.20', '20.40'], ['Thu', '9.05', '21.25'], ['Fri', '9.50', '22.10']];
