#!/usr/bin/env python3
"""From a teardown to a TREATMENT.md skeleton: the source's beats, the numbers to carry over, a script budget, and the sections DIRECTOR.md §4 asks for.

  .venv/bin/python tools/teardown/treatment.py <teardown dir> --topic "天空为什么是蓝的" [--style doodle-science] [--target 60] [--out films/x/TREATMENT.md] [--lang zh|en]

Reads <teardown dir>/teardown.json (from tools/teardown/teardown.py). Writes a draft with:
  · the source's beats: neighbouring short shots merged into one beat, each with length, share of the film, a GUESSED role (hook / body / turn / payoff),
    words said, on-screen text, camera and main colours;
  · numbers to carry over: cuts per minute, speech rate, how soon speech starts, shots in the first 3 s, where the captions sit;
  · structure A (mirror the source beat by beat, scaled to --target) with a seconds and a character budget per beat, ready to fill with YOUR sentences;
    B and C left for you (DIRECTOR.md §4 wants three);
  · empty sections for logline, shot list, beat sheet, cue map, sound table and subtitle design, each with a hint taken from the measurements.
It measures and arranges; it does not judge. Roles are guesses from position and punctuation. The source's own words appear only so you can see how its
information arrives: do not reuse them (TEARDOWN.md)."""
import argparse, json, os, re, statistics, sys
ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
ap.add_argument('teardown'); ap.add_argument('--topic', required=True); ap.add_argument('--style'); ap.add_argument('--target', type=float)
ap.add_argument('--out'); ap.add_argument('--lang', choices=['zh', 'en'])
A = ap.parse_args()
p = A.teardown if A.teardown.endswith('.json') else os.path.join(A.teardown, 'teardown.json')
if not os.path.isfile(p): sys.exit('treatment: no teardown.json in ' + A.teardown + ' (run tools/teardown/teardown.py first)')
D = json.load(open(p, encoding='utf8')); F = D['facts']; SH = D['shots']; SP = D.get('speech', [])
lang = A.lang or ('zh' if (F.get('audio') or {}).get('language', 'en').startswith('zh') else 'en')
zh = lang == 'zh'
L = lambda a, b: a if zh else b
dur = F['duration']; target = A.target or round(dur)
aud = F.get('audio') or {}
cps = aud.get('chars_per_sec') or (5.0 if zh else 14.0); share = aud.get('speech_share') or .9
unit = L('字', 'characters')

# ── beats: merge shots shorter than 2 s into the next one
beats = []; cur = None
for s in SH:
    if cur is None: cur = dict(t0=s['t0'], t1=s['t1'], shots=[s])
    else: cur['t1'] = s['t1']; cur['shots'].append(s)
    if cur['t1'] - cur['t0'] >= 2.0: beats.append(cur); cur = None
if cur:
    if beats: beats[-1]['t1'] = cur['t1']; beats[-1]['shots'] += cur['shots']
    else: beats.append(cur)
UI = re.compile(r'^[\d:：/\s.,，+\-]+$')
def said(t0, t1): return ''.join(x['text'] for x in SP if x['t0'] >= t0 - .05 and x['t0'] < t1)
def texts(b):
    seen = []
    for s in b['shots']:
        for x in s.get('text', []):
            t = x['text'].strip()
            if len(t) >= 3 and not UI.match(t) and t not in seen and .08 < x['y'] < .9: seen.append(t)
    return seen
for i, b in enumerate(beats):
    b['len'] = b['t1'] - b['t0']; b['said'] = said(b['t0'], b['t1']); b['chars'] = len(re.sub(r'\s', '', b['said'])); b['text'] = texts(b)
    q = '?' in b['said'] or '？' in b['said'] or any(w in b['said'] for w in ('为什么', '为啥', '凭啥', '怎么', 'why', 'how'))
    b['role'] = L('钩子', 'hook') if i == 0 else (L('收束', 'payoff') if i == len(beats) - 1 else (L('转折/提问', 'turn/question') if q else L('展开', 'body')))
    big = max(b['shots'], key=lambda s: s['len']); b['camera'] = big.get('camera', ''); b['pal'] = ' '.join(big.get('palette', [])[:3])
    b['key'] = big.get('keyframe', '')
# captions: where do the longest on-screen lines sit?
ys = []
for s in SH:
    c = [x for x in s.get('text', []) if .5 < x['y'] < .88 and len(x['text']) >= 6]
    if c: ys.append(max(c, key=lambda x: len(x['text']))['y'])
cap_y = statistics.median(ys) if ys else None

# ── write
o = []
w = o.append
w(L(f'# 处理稿草稿：{A.topic}', f'# Treatment draft: {A.topic}'))
w('')
w(L('> 由 `tools/teardown/treatment.py` 从拆解结果生成。下面的"角色"是按位置和标点猜的，数字是量出来的，其余是留给你写的空格。', '> Generated by `tools/teardown/treatment.py` from a teardown. Roles are guesses from position and punctuation; numbers are measured; the rest is blanks for you.'))
w('')
w(L(f'参考片：`{F["file"]}`，{F["size"][0]}×{F["size"][1]}，{dur:.1f} 秒。目标片长 {target} 秒。' + (f'风格：`{A.style}`。' if A.style else '风格：（待定，见 styles/README.md）。'),
    f'Source: `{F["file"]}`, {F["size"][0]}×{F["size"][1]}, {dur:.1f} s. Target length {target} s.' + (f' Style: `{A.style}`.' if A.style else ' Style: undecided (styles/README.md).')))
w('')
w(L('## 0. 要带走的数字', '## 0. Numbers to carry over'))
w('')
w(L('| 项 | 参考片 | 说明 |', '| item | source | note |')); w('|---|---|---|')
w(L(f'| 镜头 / 节拍 | {F["shots"]} 个镜头，合并成 {len(beats)} 个节拍 | 短于 2 秒的镜头并入下一个 |', f'| shots / beats | {F["shots"]} shots, merged into {len(beats)} beats | shots under 2 s join the next |'))
w(L(f'| 切镜速度 | {F["cuts_per_min"]} 次/分，平均 {F["mean_shot_s"]} 秒，中位 {F["median_shot_s"]} 秒 | 平均远大于中位说明有一两个很长的镜头 |', f'| cutting | {F["cuts_per_min"]} cuts/min, mean {F["mean_shot_s"]} s, median {F["median_shot_s"]} s | mean far above median = one or two long takes |'))
w(L(f'| 开头 3 秒 | {F["first3s_shots"]} 个镜头，{F["speech_starts_s"]} 秒开口 | 钩子要多快出现 |', f'| first 3 s | {F["first3s_shots"]} shots, speech at {F["speech_starts_s"]} s | how fast the hook lands |'))
w(L(f'| 语速 | {cps} {unit}/秒，说话占 {share * 100:.0f}% | 下面的字数预算按这个算 |', f'| speech | {cps} {unit}/s, {share * 100:.0f}% of the time | the budget below uses it |'))
if aud.get('mean_db') is not None: w(L(f'| 响度 | 平均 {aud["mean_db"]} dB，起伏 {aud.get("loud_range_db")} dB | 参考，不是目标；成片按 -14 LUFS | ', f'| level | mean {aud["mean_db"]} dB, range {aud.get("loud_range_db")} dB | reference only; the film masters to -14 LUFS |'))
w(L(f'| 字幕 | {"疑似烧录字幕" if F.get("burned_captions_guess") else "未发现烧录字幕"}' + (f'，大约在画面高度 {cap_y * 100:.0f}% 处' if cap_y else '') + ' | 字幕版式属于风格的一部分 |', f'| captions | {"looks burned-in" if F.get("burned_captions_guess") else "none found"}' + (f', at about {cap_y * 100:.0f}% of the height' if cap_y else '') + ' | caption design is part of the style |'))
w('')
w(L('## 1. 参考片的节拍', '## 1. The source\'s beats'))
w('')
w(L('"原话"只用来看信息怎么到达，不要用。', 'The words are shown only to see how information arrives. Do not reuse them.'))
w('')
w(L('| # | 时间 | 长度 | 占比 | 角色（猜） | 字数 | 画面文字（条） | 镜头 | 原话 |', '| # | time | len | share | role (guess) | chars | on-screen text (n) | camera | words said |')); w('|---|---|---|---|---|---|---|---|---|')
for i, b in enumerate(beats, 1):
    ex = b['said'][:34] + ('…' if len(b['said']) > 34 else '')
    w(f'| {i} | {b["t0"]:.1f}–{b["t1"]:.1f} | {b["len"]:.1f} | {b["len"] / dur * 100:.0f}% | {b["role"]} | {b["chars"]} | {len(b["text"])} | {b["camera"]} | {ex} |')
w('')
w(L('关键帧：' + '、'.join(f'`{b["key"]}`' for b in beats if b['key']) + '（在拆解目录里）。', 'Keyframes: ' + ', '.join(f'`{b["key"]}`' for b in beats if b['key']) + ' (in the teardown folder).'))
w('')
w(L('## 2. 三个候选结构', '## 2. Three candidate structures'))
w('')
w(L('### A. 镜像：照参考片的节拍走一遍，换成你的题材', '### A. Mirror: the source\'s beats, your topic'))
w('')
k = target / dur
w(L(f'每个节拍的秒数按 {k:.2f} 倍缩放；字数预算 = 秒数 × {cps} × {share:.2f}。在最后一列写你自己的句子，写完数一下字数。', f'Seconds are the source\'s scaled by {k:.2f}; the {unit} budget is seconds × {cps} × {share:.2f}. Write your own sentences in the last column and count them.'))
w('')
w(L(f'| # | 角色 | 秒 | 字数预算 | 这一段要让观众得到什么 | 你的句子 |', f'| # | role | s | {unit} budget | what the viewer should get | your sentence |')); w('|---|---|---|---|---|---|')
tot_s = 0; tot_c = 0
for i, b in enumerate(beats, 1):
    s = b['len'] * k; c = round(s * cps * share); tot_s += s; tot_c += c
    w(f'| {i} | {b["role"]} | {s:.1f} | {c} | TODO | TODO |')
w(L(f'| 合计 | | {tot_s:.1f} | {tot_c} | | |', f'| total | | {tot_s:.1f} | {tot_c} | | |'))
w('')
w(L('### B. TODO（换一种叙事形状，例如先给结论再解释、倒叙、清单递进）', '### B. TODO (another shape: answer first, flashback, a list that turns)'))
w('')
w(L('### C. TODO', '### C. TODO'))
w('')
w(L('### 选择与理由', '### Choice and why'))
w('')
w('TODO')
w('')
w(L('## 3. 一句话和弧线', '## 3. Logline and arc')); w(''); w(L('TODO（一句话；开头 → 转折 → 结尾）', 'TODO (one sentence; setup → turn → ending)')); w('')
w(L('## 4. 对标：学什么、不学什么', '## 4. Benchmark: learn / don\'t learn')); w('')
w(L('- 学：节拍顺序与长度、钩子到来的速度、语速、字幕所在的位置和样式、切镜节奏。', '- Learn: the order and length of beats, how fast the hook lands, speech rate, where and how captions sit, the cutting rhythm.'))
w(L('- 不学：参考片的画面、角色、品牌标志、文案、配音、音乐、界面截图（若是录屏，连手机界面也不要）。', '- Don\'t: its pictures, characters, brand marks, script, voice, music, interface (if it is a screen recording, not the phone UI either).'))
w('')
w(L('## 5. 分镜表', '## 5. Shot list')); w('')
w(L('| # | 节拍 | 景别 | 机位/运动 | 秒 | 为什么这样拍 |', '| # | beat | framing | camera | s | why |')); w('|---|---|---|---|---|---|'); w('| TODO | | | | | |'); w('')
w(L('参考片的机位：' + '、'.join(sorted({b['camera'] for b in beats if b['camera']})) + '。', 'Source camera: ' + ', '.join(sorted({b['camera'] for b in beats if b['camera']})) + '.')); w('')
w(L('## 6. 节拍表（逐秒）', '## 6. Beat sheet (second by second)')); w(''); w('TODO'); w('')
w(L('## 7. 配乐与提示点', '## 7. Cue map')); w('')
w(L('参考片的速度估计：' + (str(aud.get('tempo_bpm_guess')) if aud.get('tempo_bpm_guess') else '量不出来') + '。TODO：速度、小节线、每个切镜/动作/字幕落在哪一拍。', 'Source tempo guess: ' + (str(aud.get('tempo_bpm_guess')) if aud.get('tempo_bpm_guess') else 'not measurable') + '. TODO: tempo, bar grid, which beat every cut, action and caption lands on.')); w('')
w(L('## 8. 声音设计表', '## 8. Sound design table')); w(''); w(L('| 段 | 环境声 | 主要拟音 | 音乐状态 |', '| section | ambience | main foley | music state |')); w('|---|---|---|---|'); w('| TODO | | | |'); w('')
w(L('## 9. 字幕与字', '## 9. Subtitle and title design')); w('')
w(L('- 参考：' + ('烧录字幕' if F.get('burned_captions_guess') else '无烧录字幕') + (f'，位置约 {cap_y * 100:.0f}% 高度' if cap_y else '') + '。', '- Source: ' + ('burned-in captions' if F.get('burned_captions_guess') else 'no burned-in captions') + (f', at about {cap_y * 100:.0f}% of the height' if cap_y else '') + '.'))
w(L('- TODO：字体（OFL）、字号、描边、每句停留时间（口播同步字幕会被 readcheck 报"太短"，要在处理稿里说明）。', '- TODO: face (OFL), size, outline, hold time per line (voice-synced captions will be flagged by readcheck; say so here).'))
w('')
w(L('## 10. 事实与来源', '## 10. Facts and sources')); w(''); w(L('TODO：片里每个数字和断言的出处（见 `FACTS.md` / `facts.md`）。', 'TODO: the source of every number and claim in the film (`FACTS.md` / `facts.md`).')); w('')
out = A.out or os.path.join(os.path.dirname(os.path.abspath(p)), '..', 'TREATMENT.md')
out = os.path.abspath(out)
if os.path.exists(out) and not os.environ.get('FORCE'):
    alt = out[:-3] + '.draft.md'; print('treatment:', out, 'exists; writing', alt, '(set FORCE=1 to overwrite)'); out = alt
open(out, 'w', encoding='utf8').write('\n'.join(o) + '\n')
print('wrote', out, f'({len(beats)} beats, budget {tot_c} {unit} for {target} s)')
