window.GALLERY = {
 "styles": [
  {
   "slug": "crayon-book",
   "num": "01",
   "en": "Crayon Picture Book",
   "cn": "蜡笔儿童绘本",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "The Moon Can't Sleep",
   "line": "The moon can't sleep, so a little girl climbs onto the roof to sing it a lullaby.",
   "line_cn": "月亮失眠了，小女孩爬上屋顶给它唱摇篮曲。",
   "uses": [
    "Picture books",
    "Bedtime stories",
    "Kids' learning"
   ],
   "dur": 52.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/crayon-book.mp4",
   "frame": "../docs/frames/crayon-book.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/crayon-book/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/crayon-book/DEMO.md"
  },
  {
   "slug": "watercolor",
   "num": "02",
   "en": "Watercolor Brush",
   "cn": "水彩笔刷",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "Follow the Rain",
   "line": "Follow the rain from Australia's red desert heart to its green coast in one unbroken painted walk.",
   "line_cn": "跟着降雨从澳洲红色腹地一路画到绿色海岸，一镜到底。",
   "uses": [
    "Nature documentary",
    "Travel",
    "Science explainers"
   ],
   "dur": 113.6,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/watercolor.mp4",
   "frame": "../docs/frames/watercolor.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/watercolor/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/watercolor/DEMO.md"
  },
  {
   "slug": "ink-wash",
   "num": "03",
   "en": "Chinese Ink Wash",
   "cn": "中国水墨",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "The Swordsman and the River",
   "line": "A swordsman crosses the river on the water and splits the current with a single stroke.",
   "line_cn": "侠客踏水过江，一剑断流。",
   "uses": [
    "Wuxia",
    "Cultural brands",
    "Poetry"
   ],
   "dur": 48.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/ink-wash.mp4",
   "frame": "../docs/frames/ink-wash.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ink-wash/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ink-wash/DEMO.md"
  },
  {
   "slug": "impasto",
   "num": "04",
   "en": "Impasto Oil Painting",
   "cn": "油画厚涂",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "The Colour of Rain",
   "line": "In a grey, rainy square one red umbrella opens, and a waltz paints the whole plaza in colour.",
   "line_cn": "灰色雨中广场，第一把红伞撑开，圆舞曲把整个广场刷上颜色。",
   "uses": [
    "Music videos",
    "Art & culture",
    "Emotional ads"
   ],
   "dur": 39.7,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/impasto.mp4",
   "frame": "../docs/frames/impasto.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/impasto/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/impasto/DEMO.md"
  },
  {
   "slug": "one-line",
   "num": "05",
   "en": "One-line Drawing",
   "cn": "一笔画",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "The Line That Never Lifted",
   "line": "One unbroken line draws a whole life, then the pen passes to a child.",
   "line_cn": "一根不离纸的线画完一个人的一生，再把笔交给孩子。",
   "uses": [
    "Brand stories",
    "Life milestones",
    "Minimal ads"
   ],
   "dur": 47.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/one-line.mp4",
   "frame": "../docs/frames/one-line.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/one-line/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/one-line/DEMO.md"
  },
  {
   "slug": "whiteboard",
   "num": "06",
   "en": "Whiteboard Explainer",
   "cn": "白板讲解",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "Einstein in Your Pocket",
   "line": "How your phone knows where you are: GPS, atomic clocks, and the 38 microseconds relativity adds every day.",
   "line_cn": "手机怎么知道你在哪：GPS、原子钟，和相对论每天多出的 38 微秒。",
   "uses": [
    "Explainers",
    "Online courses",
    "Science"
   ],
   "dur": 111.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/whiteboard.mp4",
   "frame": "../docs/frames/whiteboard.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/whiteboard/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/whiteboard/DEMO.md"
  },
  {
   "slug": "urban-sketch",
   "num": "45",
   "en": "Urban Sketch · Pen & Wash",
   "cn": "钢笔淡彩",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "Where the Wind Went",
   "line": "A park that is only a pen sketch; wherever the wind carries her straw hat, colour follows.",
   "line_cn": "公园只是一张钢笔速写，风把草帽吹到哪里，哪里才有颜色。",
   "uses": [
    "City & travel",
    "Architecture",
    "Lifestyle brands"
   ],
   "dur": 32.4,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/urban-sketch.mp4",
   "frame": "../docs/frames/urban-sketch.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/urban-sketch/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/urban-sketch/DEMO.md"
  },
  {
   "slug": "embroidery",
   "num": "56",
   "en": "Embroidery & Knit",
   "cn": "刺绣与针织",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "Every Mend Begins with a Hole",
   "line": "A worn knit elbow is darned, a flower grows stitch by stitch over the darn, and the mended sleeve walks out the door.",
   "line_cn": "针织袖肘磨出一个洞，先织补，再一针一针在上面绣出一朵花，补好的袖子走出了门。",
   "uses": [
    "Craft and repair stories",
    "Gentle brand films",
    "Seasonal greetings and keepsakes"
   ],
   "dur": 50,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/embroidery.mp4",
   "frame": "../docs/frames/embroidery.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/embroidery/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/embroidery/DEMO.md"
  },
  {
   "slug": "charcoal",
   "num": "64",
   "en": "Charcoal Sketch Animation",
   "cn": "木炭素描动画",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "The Bend",
   "line": "One pinned sheet keeps nine years of a river: each spring the bank is rubbed out and redrawn nearer the house, the ghosts stay, and the red door is finally moved uphill.",
   "line_cn": "同一张图钉固定的纸记下一条河的九年：每年春天河岸被擦掉、重画得离房子更近，旧岸的幽灵留在纸上，最后那扇红门被搬到了山坡上。",
   "uses": [
    "Memory and time-passing stories",
    "Documentary and place portraits",
    "Quiet explainers about change and loss"
   ],
   "dur": 57,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/charcoal.mp4",
   "frame": "../docs/frames/charcoal.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/charcoal/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/charcoal/DEMO.md"
  },
  {
   "slug": "sand-animation",
   "num": "70",
   "en": "Sand Animation",
   "cn": "沙画",
   "cat": "手绘与绘画",
   "cat_en": "Hand-drawn & Painting",
   "film": "Where the Sparrow Went",
   "line": "A stream of sand builds a heap that rises into a tree, flies off as a bird, breaks as a wave, stands as a lighthouse and falls back into a heap that spells home, with no cut.",
   "line_cn": "一道沙流堆成沙丘，沙丘长成大树，大树化作飞鸟，飞鸟翻成海浪，海浪立成灯塔，最后落回沙丘，拼出一个“home”，全程没有一次剪切。",
   "uses": [
    "Life stories & memorials",
    "Brand origins & journeys",
    "Seasons, time & change"
   ],
   "dur": 58.4,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/sand-animation.mp4",
   "frame": "../docs/frames/sand-animation.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/sand-animation/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/sand-animation/DEMO.md"
  },
  {
   "slug": "shadow-puppet",
   "num": "07",
   "en": "Shadow Puppetry",
   "cn": "皮影戏",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "Hou Yi Shoots the Suns",
   "line": "Ten suns scorch the earth until the archer Hou Yi draws his bow, told with leather puppets on a lit screen.",
   "line_cn": "十日炙烤大地，后羿张弓射日。",
   "uses": [
    "Myths & folklore",
    "Heritage",
    "Festivals"
   ],
   "dur": 54.4,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/shadow-puppet.mp4",
   "frame": "../docs/frames/shadow-puppet.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/shadow-puppet/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/shadow-puppet/DEMO.md"
  },
  {
   "slug": "ukiyoe",
   "num": "08",
   "en": "Ukiyo-e",
   "cn": "浮世绘",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "A Journey Toward the Mountain",
   "line": "A traveller walks toward a distant mountain; every shot is a woodblock print, ending in a great wave.",
   "line_cn": "旅人走向远山，每个镜头都是一幅版画，最后迎来一道巨浪。",
   "uses": [
    "Travel",
    "Japanese culture",
    "Poetry"
   ],
   "dur": 44.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/ukiyoe.mp4",
   "frame": "../docs/frames/ukiyoe.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ukiyoe/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ukiyoe/DEMO.md"
  },
  {
   "slug": "papercut-red",
   "num": "09",
   "en": "Red Paper-cut",
   "cn": "红色窗花剪纸",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "Nian Comes to Town",
   "line": "On New Year's Eve the beast Nian comes to town, and one girl's giant paper-cut lights up the village to scare it off.",
   "line_cn": "除夕年兽进村，小女孩剪出的大窗花照亮全村，把它吓跑。",
   "uses": [
    "Lunar New Year",
    "Festive greetings",
    "Folk tales"
   ],
   "dur": 49.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/papercut-red.mp4",
   "frame": "../docs/frames/papercut-red.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/papercut-red/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/papercut-red/DEMO.md"
  },
  {
   "slug": "paper-lantern",
   "num": "10",
   "en": "Paper-cut Lightbox",
   "cn": "纸雕灯影",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "A Mooncake's Longing",
   "line": "A single mooncake tells the Mid-Autumn story of reunion and longing inside a glowing paper-cut lightbox.",
   "line_cn": "一枚月饼讲中秋的团圆与思念，纸雕灯箱层层透光。",
   "uses": [
    "Festivals",
    "Gift brands",
    "Cultural stories"
   ],
   "dur": 121.8,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/paper-lantern.mp4",
   "frame": "../docs/frames/paper-lantern.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/paper-lantern/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/paper-lantern/DEMO.md"
  },
  {
   "slug": "blue-white",
   "num": "68",
   "en": "Blue-and-White Porcelain",
   "cn": "青花瓷",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "The Blue Only Arrives in the Fire",
   "line": "A brush paints a river round a turning vase, the camera falls through its rim into the painted landscape, and the kiln turns grey strokes to blue.",
   "line_cn": "一支笔在转动的瓷瓶上画出一条河，镜头从瓶口落进画里的山水，入窑一烧，灰色笔痕变成青蓝。",
   "uses": [
    "Cultural and heritage stories",
    "Craft, tea and tableware brands",
    "Poetry and landscape narratives"
   ],
   "dur": 54.0,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/blue-white.mp4",
   "frame": "../docs/frames/blue-white.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/blue-white/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/blue-white/DEMO.md"
  },
  {
   "slug": "dunhuang",
   "num": "69",
   "en": "Dunhuang Mural",
   "cn": "敦煌壁画",
   "cat": "东方传统",
   "cat_en": "East Asian Traditions",
   "film": "Borrowed Lamplight",
   "line": "A borrowed oil lamp walks along a cave wall; every register it passes wakes from weathered plaster to its first colour, and when the flame sinks the wall remembers.",
   "line_cn": "借来的一盏油灯沿着洞窟墙壁走过，灯光所到之处，褪色的壁画一层层醒回最初的颜色；火苗落下时，墙还记得。",
   "uses": [
    "Heritage and museum films",
    "Silk-road, tea and craft origin stories",
    "Festival, calligraphy and pattern-design brands"
   ],
   "dur": 53.3,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/dunhuang.mp4",
   "frame": "../docs/frames/dunhuang.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dunhuang/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dunhuang/DEMO.md"
  },
  {
   "slug": "risograph",
   "num": "12",
   "en": "Risograph Print",
   "cn": "Risograph 丝网印刷",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "Sunday Ride",
   "line": "A Sunday-morning bike ride through the city — bakery, park, riverside — in two misregistered inks.",
   "line_cn": "周日早晨骑车穿过城市：面包店、公园、河边。",
   "uses": [
    "Indie brands",
    "Zines",
    "Lifestyle"
   ],
   "dur": 40.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/risograph.mp4",
   "frame": "../docs/frames/risograph.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/risograph/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/risograph/DEMO.md"
  },
  {
   "slug": "halftone-dossier",
   "num": "13",
   "en": "Halftone Dossier",
   "cn": "复古半调案卷",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "Case File: Chubby",
   "line": "A chubby orange cat stands trial for testing gravity and 4 a.m. parkour, and walks free.",
   "line_cn": "橘猫胖橘被立案审查：测试重力、凌晨跑酷，最后无罪释放。",
   "uses": [
    "Humour",
    "Pet content",
    "Social shorts"
   ],
   "dur": 30.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/halftone-dossier.mp4",
   "frame": "../docs/frames/halftone-dossier.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/halftone-dossier/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/halftone-dossier/DEMO.md"
  },
  {
   "slug": "woodcut",
   "num": "15",
   "en": "Woodcut Print",
   "cn": "木刻版画",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "The Bell Founder",
   "line": "A village spends a whole winter casting one bell; the first time it rings, the snow stops.",
   "line_cn": "村子用一整个冬天铸一口钟，钟声第一次响起，雪停了。",
   "uses": [
    "Folk tales",
    "Craft brands",
    "Book trailers"
   ],
   "dur": 58.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/woodcut.mp4",
   "frame": "../docs/frames/woodcut.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/woodcut/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/woodcut/DEMO.md"
  },
  {
   "slug": "engraving",
   "num": "53",
   "en": "Copperplate Engraving",
   "cn": "铜版画",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "The Honeybee, Plate VII",
   "line": "A natural-history plate engraves itself: the burin cuts the copper, the bee builds up line by line, and a watercolour wash brings it to life.",
   "line_cn": "一张博物志图版自己刻出来：雕刀推开铜版，蜜蜂一线线成形，最后手工水彩上色。",
   "uses": [
    "Museum labels",
    "Science explainers",
    "Brand heritage"
   ],
   "dur": 40.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/engraving.mp4",
   "frame": "../docs/frames/engraving.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/engraving/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/engraving/DEMO.md"
  },
  {
   "slug": "silkscreen-poster",
   "num": "54",
   "en": "Silkscreen Travel Poster",
   "cn": "丝印旅行海报",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "Three Trails",
   "line": "Three trail posters are screen-printed one ink at a time, then climbed in one long take from noon to dusk.",
   "line_cn": "三条步道各一张丝印海报，一色一刮印出来，再沿山脊一镜到底从正午爬到黄昏。",
   "uses": [
    "Trail & destination guides",
    "Tourism promos",
    "Event posters"
   ],
   "dur": 38.4,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/silkscreen-poster.mp4",
   "frame": "../docs/frames/silkscreen-poster.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/silkscreen-poster/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/silkscreen-poster/DEMO.md"
  },
  {
   "slug": "natural-history",
   "num": "60",
   "en": "Natural History Plate",
   "cn": "博物图鉴",
   "cat": "印刷与版画",
   "cat_en": "Print & Printmaking",
   "film": "Plate IV: The Spiral, in Four Makers",
   "line": "A blank sheet fills with a hand-coloured plate: a chambered shell is drawn, halved and magnified, then a snail, a sunflower head and a fern crozier join it, each pinned, until the page curls away.",
   "line_cn": "一张空白图版被一笔笔画满：鹦鹉螺先被画出、剖开、放大，随后蜗牛、向日葵花盘和蕨类拳卷幼叶依次画好并钉住，最后整页被翻走。",
   "uses": [
    "Museum and science-communication explainers",
    "Species, anatomy and process 'field guide' films",
    "Product or ingredient catalogues dressed as scientific plates"
   ],
   "dur": 60,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/natural-history.mp4",
   "frame": "../docs/frames/natural-history.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/natural-history/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/natural-history/DEMO.md"
  },
  {
   "slug": "swiss-motion",
   "num": "16",
   "en": "Swiss Motion Graphics",
   "cn": "瑞士动态排版",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Five Rules for a Poster",
   "line": "A concert poster lays itself out by five Swiss design rules; the fifth is to break just one.",
   "line_cn": "一张音乐会海报按瑞士设计的五条规则自己排版，第五条是只打破一条。",
   "uses": [
    "Brand identity",
    "Events",
    "Design education"
   ],
   "dur": 44.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/swiss-motion.mp4",
   "frame": "../docs/frames/swiss-motion.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/swiss-motion/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/swiss-motion/DEMO.md"
  },
  {
   "slug": "spy-titles",
   "num": "17",
   "en": "60s Spy Title Sequence",
   "cn": "60s 间谍片头",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "The Velvet Cipher",
   "line": "Opening titles for an imaginary 1964 spy film: a chase for a stolen key until the shapes lock into the title.",
   "line_cn": "虚构 1964 年间谍片的片头：追一把被偷的钥匙，几何碎片最后拼成片名。",
   "uses": [
    "Title sequences",
    "Event openers",
    "Trailers"
   ],
   "dur": 44.1,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/spy-titles.mp4",
   "frame": "../docs/frames/spy-titles.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/spy-titles/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/spy-titles/DEMO.md"
  },
  {
   "slug": "art-deco",
   "num": "18",
   "en": "Art Deco",
   "cn": "装饰艺术",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Midnight at the Starlight Hotel",
   "line": "A grand hotel, 1930: a bellboy races lifts and revolving doors to deliver one letter before midnight.",
   "line_cn": "1930 年的大饭店，门童赶在午夜前把一封信送上顶楼。",
   "uses": [
    "Luxury & hospitality",
    "Galas",
    "Invitations"
   ],
   "dur": 58.4,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/art-deco.mp4",
   "frame": "../docs/frames/art-deco.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/art-deco/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/art-deco/DEMO.md"
  },
  {
   "slug": "blueprint",
   "num": "19",
   "en": "Blueprint",
   "cn": "蓝图 / 工程制图",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Patent Pending: The Cloud Catcher",
   "line": "An inventor's blueprint draws, explodes and assembles a cloud-catching machine, and its revision cloud starts to rain.",
   "line_cn": "发明家的蓝图自己画出一台接云机器，修订云线变成了真的雨云。",
   "uses": [
    "Engineering",
    "Hardware launches",
    "Tech explainers"
   ],
   "dur": 46.7,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/blueprint.mp4",
   "frame": "../docs/frames/blueprint.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/blueprint/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/blueprint/DEMO.md"
  },
  {
   "slug": "stained-glass",
   "num": "20",
   "en": "Stained Glass",
   "cn": "彩色玻璃窗",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "The Dragon of the East Window",
   "line": "Sunlight crosses a cathedral window from dawn to dusk, waking each pane of a knight-and-dragon tale.",
   "line_cn": "阳光从清晨移到黄昏，照到哪一格花窗，哪一格的故事就动起来。",
   "uses": [
    "Legends",
    "Heritage",
    "Holiday stories"
   ],
   "dur": 56.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/stained-glass.mp4",
   "frame": "../docs/frames/stained-glass.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/stained-glass/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/stained-glass/DEMO.md"
  },
  {
   "slug": "pictogram-motion",
   "num": "21",
   "en": "Pictogram Motion",
   "cn": "象形运动图形",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Aichi-Nagoya 2026 — All 43 Sports",
   "line": "All 43 sports of the 2026 Asian Games as beat-locked geometric pictograms.",
   "line_cn": "2026 亚运会 43 个大项，几何象形人卡着节拍快闪。",
   "uses": [
    "Sports events",
    "Visual identity",
    "Event openers"
   ],
   "dur": 163.6,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/pictogram-motion.mp4",
   "frame": "../docs/frames/pictogram-motion.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pictogram-motion/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pictogram-motion/DEMO.md"
  },
  {
   "slug": "ascii-crt",
   "num": "22",
   "en": "ASCII / CRT Terminal",
   "cn": "ASCII / CRT 终端",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Tranquility.log",
   "line": "A moon-base AI wakes after forty years to a signal from Earth, and replies by drawing “home” in characters.",
   "line_cn": "月球基地的 AI 沉睡 40 年后被唤醒，用字符画出“家”来回复。",
   "uses": [
    "Developer tools",
    "Sci-fi",
    "Tech brands"
   ],
   "dur": 59.8,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/ascii-crt.mp4",
   "frame": "../docs/frames/ascii-crt.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ascii-crt/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/ascii-crt/DEMO.md"
  },
  {
   "slug": "neon-sign",
   "num": "58",
   "en": "Neon Signage",
   "cn": "霓虹灯牌",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "The Last Bowl on Pell Street",
   "line": "A noodle bar's neon sign is lit tube by tube at dusk, loses one stroke of a letter in the small hours, and is switched off to grey glass at dawn.",
   "line_cn": "一家面馆的霓虹灯牌被一根根点亮，后半夜一个字母的笔画永远熄了，天亮时被一只手拉闸，只剩灰色的玻璃管。",
   "uses": [
    "Bars, diners & night economy",
    "Openings, countdowns & event teasers",
    "Brand and slogan reveals"
   ],
   "dur": 54.0,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/neon-sign.mp4",
   "frame": "../docs/frames/neon-sign.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/neon-sign/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/neon-sign/DEMO.md"
  },
  {
   "slug": "art-nouveau",
   "num": "62",
   "en": "Art Nouveau",
   "cn": "新艺术",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "The Iris Hour",
   "line": "A single gilded line becomes a vine that carries us past three arched windows, from a frosted bud to an iris in bloom, and the title is lettered out of its stem.",
   "line_cn": "一根鎏金的线变成藤蔓，带我们穿过三扇拱窗，从结霜的花苞走到盛开的鸢尾，片名就从花茎里写出来。",
   "uses": [
    "Botanical, perfume & beauty brands",
    "Theatre, concerts & exhibitions",
    "Seasonal and nature storytelling"
   ],
   "dur": 52.5,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/art-nouveau.mp4",
   "frame": "../docs/frames/art-nouveau.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/art-nouveau/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/art-nouveau/DEMO.md"
  },
  {
   "slug": "constructivist",
   "num": "63",
   "en": "Bauhaus & Constructivist Poster",
   "cn": "包豪斯构成主义",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Thirty Metres",
   "line": "A relay poster builds itself block by block on a steep diagonal, and the whole film narrows to the one place a race is won: the thirty-metre box where the baton changes hands.",
   "line_cn": "一张接力赛海报沿陡峭的对角线一块一块搭起来，整部片子收窄到决定胜负的那 30 米交接区：接力棒在这里换手。",
   "uses": [
    "Event and campaign announcements",
    "Stage-by-stage process explainers",
    "Sports, civic and maker stories"
   ],
   "dur": 52.0,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/constructivist.mp4",
   "frame": "../docs/frames/constructivist.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/constructivist/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/constructivist/DEMO.md"
  },
  {
   "slug": "y2k-vaporwave",
   "num": "71",
   "en": "Vaporwave & Y2K Chrome",
   "cn": "蒸汽波与 Y2K",
   "cat": "图形与排版",
   "cat_en": "Graphic & Type",
   "film": "Installing Summer",
   "line": "A setup wizard installs one summer: the bar crawls under a sinking banded sun, hangs at 99 % in silence, then completes in spinning chrome type before the last dialog is dismissed.",
   "line_cn": "一个安装向导在安装一个夏天：进度条在沉落的条纹夕阳下爬行，静默中卡在 99%，然后以旋转的铬金属字完成，最后点掉最后一个对话框。",
   "uses": [
    "Nostalgia, music and album-style visuals",
    "Fashion, lifestyle and youth-culture brands",
    "Launch teasers, countdowns and loading-screen stories"
   ],
   "dur": 49.4,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/y2k-vaporwave.mp4",
   "frame": "../docs/frames/y2k-vaporwave.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/y2k-vaporwave/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/y2k-vaporwave/DEMO.md"
  },
  {
   "slug": "dataviz",
   "num": "23",
   "en": "Data Storytelling",
   "cn": "数据叙事",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "A Hundred Summers",
   "line": "A hundred years of summer temperatures, where the chart itself tells the story.",
   "line_cn": "一百年的夏季气温，图表本身就是故事。",
   "uses": [
    "Data journalism",
    "Reports",
    "Climate & science"
   ],
   "dur": 50.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/dataviz.mp4",
   "frame": "../docs/frames/dataviz.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dataviz/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dataviz/DEMO.md"
  },
  {
   "slug": "iso-infographic",
   "num": "24",
   "en": "Isometric Infographic",
   "cn": "等距信息图",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "From Bean to Cup",
   "line": "A coffee's journey from the plantation to your hands, across one isometric world.",
   "line_cn": "一杯咖啡从种植园到你手里的旅程。",
   "uses": [
    "Process explainers",
    "Supply chains",
    "Annual reports"
   ],
   "dur": 58.8,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/iso-infographic.mp4",
   "frame": "../docs/frames/iso-infographic.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/iso-infographic/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/iso-infographic/DEMO.md"
  },
  {
   "slug": "dark-keynote",
   "num": "25",
   "en": "Dark Tech Keynote",
   "cn": "暗色科技发布",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "Room to Think",
   "line": "Launch film for Tidy, a fictional app: one buried cursor snaps hundreds of windows back into place.",
   "line_cn": "虚构 app Tidy 的发布片：被埋掉的光标一键把几百个窗口归位。",
   "uses": [
    "Product launches",
    "SaaS",
    "Keynotes"
   ],
   "dur": 42.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/dark-keynote.mp4",
   "frame": "../docs/frames/dark-keynote.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dark-keynote/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/dark-keynote/DEMO.md"
  },
  {
   "slug": "living-screencast",
   "num": "46",
   "en": "Living Screencast",
   "cn": "活体实机录屏",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "Clawd Moves In",
   "line": "Clawd, the Claude Code pixel mascot, hops out of the terminal into the Claude app and acts out plan mode, diff comments and self-checks in a one-take screencast.",
   "line_cn": "像素小人 Clawd 跳出终端、搬进 Claude 应用，在一镜到底的录屏里演示 Plan 模式、diff 评论和自检。",
   "uses": [
    "Product tutorials",
    "Feature launches",
    "Onboarding"
   ],
   "dur": 59.4,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/living-screencast.mp4",
   "frame": "../docs/frames/living-screencast.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/living-screencast/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/living-screencast/DEMO.md"
  },
  {
   "slug": "hologram-hud",
   "num": "52",
   "en": "Sci-fi Hologram HUD",
   "cn": "科幻全息界面",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "Volt · Spec Scan",
   "line": "An e-bike is scanned into a hologram; target boxes lock onto the battery, motor and brakes, and each spec rolls into place.",
   "line_cn": "一辆电助力车被扫描成全息线框，目标框依次锁定电池、电机、刹车，参数逐个滚到真值。",
   "uses": [
    "Product spec walkthroughs",
    "Launch & crowdfunding videos",
    "Trade-show screens"
   ],
   "dur": 39.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/hologram-hud.mp4",
   "frame": "../docs/frames/hologram-hud.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/hologram-hud/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/hologram-hud/DEMO.md"
  },
  {
   "slug": "sheet-music",
   "num": "66",
   "en": "Sheet-music Motion",
   "cn": "乐谱音乐可视化",
   "cat": "信息与发布",
   "cat_en": "Information & Keynote",
   "film": "Four Notes",
   "line": "A four-note seed is repeated, mirrored and stretched on an engraved page, then the page unrolls into a landscape where the same score blooms, ripples and draws itself as ribbons.",
   "line_cn": "四个音符的动机被重复、倒影、拉长；乐谱随后铺开成风景，同一份乐谱开花、起浪、画出旋律的丝带。",
   "uses": [
    "Explaining a musical idea",
    "Podcast intro",
    "Brand sting",
    "Music lesson"
   ],
   "dur": 50.0,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/sheet-music.mp4",
   "frame": "../docs/frames/sheet-music.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/sheet-music/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/sheet-music/DEMO.md"
  },
  {
   "slug": "rubber-hose",
   "num": "26",
   "en": "1930s Rubber Hose Cartoon",
   "cn": "1930s 橡皮管卡通",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "Coffee Cup Chase",
   "line": "A coffee cup chases a runaway sugar cube around the kitchen, 1930s-cartoon style.",
   "line_cn": "一只咖啡杯满厨房追一块逃跑的方糖。",
   "uses": [
    "Food & drink",
    "Retro ads",
    "Kids"
   ],
   "dur": 50.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/rubber-hose.mp4",
   "frame": "../docs/frames/rubber-hose.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/rubber-hose/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/rubber-hose/DEMO.md"
  },
  {
   "slug": "cel-anime-80s",
   "num": "27",
   "en": "80s Cel Anime",
   "cn": "80 年代赛璐璐动画",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "City Lights, 1987",
   "line": "A courier girl rides through a rain-soaked neon city to deliver a tape before the dawn launch.",
   "line_cn": "快递少女骑车穿过雨后霓虹都市，赶在黎明发射前送到一盘磁带。",
   "uses": [
    "Music videos",
    "Game trailers",
    "Nostalgia"
   ],
   "dur": 59.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/cel-anime-80s.mp4",
   "frame": "../docs/frames/cel-anime-80s.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/cel-anime-80s/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/cel-anime-80s/DEMO.md"
  },
  {
   "slug": "scifi-toon",
   "num": "28",
   "en": "Sci-Fi Sitcom Toon",
   "cn": "科幻情景喜剧卡通",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "Coffee Run",
   "line": "A jaded genius opens a portal just to buy coffee and tumbles through ever-stranger universes.",
   "line_cn": "厌世天才开传送门只想买杯咖啡，却穿过越来越离谱的平行宇宙。",
   "uses": [
    "Comedy",
    "Tech brands",
    "Social shorts"
   ],
   "dur": 57.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/scifi-toon.mp4",
   "frame": "../docs/frames/scifi-toon.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/scifi-toon/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/scifi-toon/DEMO.md"
  },
  {
   "slug": "midcentury-toon",
   "num": "48",
   "en": "Mid-century Cartoon",
   "cn": "50s 扁平卡通",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "Meet Pip",
   "line": "A robot vacuum set up in three steps, told like a 1950s classroom film: place the dock, connect the app, press start.",
   "line_cn": "用 50 年代教育片的口吻，三步教你装好一台扫地机：放充电座、连 app、按开始。",
   "uses": [
    "Product set-up guides",
    "Help-centre explainers",
    "How-to steps"
   ],
   "dur": 40.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/midcentury-toon.mp4",
   "frame": "../docs/frames/midcentury-toon.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/midcentury-toon/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/midcentury-toon/DEMO.md"
  },
  {
   "slug": "comic-pop",
   "num": "57",
   "en": "Comic Panel Pop Art",
   "cn": "美漫分格波普",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "Butter Side Down",
   "line": "A slice of toast slides off a 75 cm table, gets exactly half a spin, and lands butter side down: the physics of Murphy's law in a comic page that builds itself panel by panel.",
   "line_cn": "一片吐司从 75 厘米高的桌边滑落，只来得及转半圈，黄油面朝下：墨菲定律背后的物理，用一页自己拼起来的美漫。",
   "uses": [
    "Explainers with a punchline",
    "Product or feature stories in beats",
    "Social shorts and ads"
   ],
   "dur": 47.1,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/comic-pop.mp4",
   "frame": "../docs/frames/comic-pop.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/comic-pop/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/comic-pop/DEMO.md"
  },
  {
   "slug": "opera-cel",
   "num": "59",
   "en": "Peking Opera Cel Animation",
   "cn": "国风戏曲动画",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "One Gong at Stone Gate",
   "line": "A young stage-warrior duels a stone spirit at a mountain gate, then opens the shut spring with one struck gong instead of her spear.",
   "line_cn": "年轻的武旦与石精在山门对阵，最后没有出枪，只敲了一记锣，封住的泉水便涌了出来。",
   "uses": [
    "Heritage and festival films",
    "Brand legends and origin stories",
    "Fables and idioms for learners"
   ],
   "dur": 52.5,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/opera-cel.mp4",
   "frame": "../docs/frames/opera-cel.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/opera-cel/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/opera-cel/DEMO.md"
  },
  {
   "slug": "manga-panel",
   "num": "67",
   "en": "Manga Panel",
   "cn": "漫画黑白网点",
   "cat": "卡通与动画",
   "cat_en": "Cartoon & Anime",
   "film": "The Last Pineapple Bun",
   "line": "A girl and a middle-aged salaryman sprint for the last pineapple bun of the day, reach it in the same second, and split it: a black-and-white manga spread read right to left, panel by panel.",
   "line_cn": "女孩和中年上班族为当天最后一个菠萝包冲刺，同一秒伸手，最后一人一半：一页从右往左、一格一格读下去的黑白漫画。",
   "uses": [
    "Comic-style explainers and how-tos",
    "Slice-of-life and gag shorts",
    "Chapter openers, trailers and social teasers"
   ],
   "dur": 55.2,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/manga-panel.mp4",
   "frame": "../docs/frames/manga-panel.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/manga-panel/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/manga-panel/DEMO.md"
  },
  {
   "slug": "pixel-rpg",
   "num": "29",
   "en": "16-bit Pixel RPG",
   "cn": "16-bit 像素 RPG",
   "cat": "游戏",
   "cat_en": "Games",
   "film": "The Last Save Point",
   "line": "At the final boss door a hero saves the game, and the save screen replays the whole journey.",
   "line_cn": "勇士在最终 Boss 门前存档，存档画面闪回一路冒险。",
   "uses": [
    "Game trailers",
    "Recaps",
    "Nostalgia"
   ],
   "dur": 54.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/pixel-rpg.mp4",
   "frame": "../docs/frames/pixel-rpg.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pixel-rpg/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pixel-rpg/DEMO.md"
  },
  {
   "slug": "hd-2d",
   "num": "31",
   "en": "HD-2D",
   "cn": "HD-2D",
   "cat": "游戏",
   "cat_en": "Games",
   "film": "The Lampbearer",
   "line": "The lighthouse goes dark; a girl carries the last flame through a night forest and up the storm cliffs.",
   "line_cn": "灯塔熄灭，孙女提着最后一簇火穿过夜林、爬上风暴悬崖。",
   "uses": [
    "Game trailers",
    "Fantasy",
    "Story films"
   ],
   "dur": 76.5,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/hd-2d.mp4",
   "frame": "../docs/frames/hd-2d.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/hd-2d/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/hd-2d/DEMO.md"
  },
  {
   "slug": "microgame",
   "num": "32",
   "en": "Microgame Frenzy",
   "cn": "微游戏快闪（瓦里奥制造式）",
   "cat": "游戏",
   "cat_en": "Games",
   "film": "Five-Second Astronaut",
   "line": "A clumsy cadet survives a five-second boot camp, faster and faster, until the boss: landing home.",
   "line_cn": "见习宇航员闯五秒训练营，越来越快，Boss 关亲手降落回地球。",
   "uses": [
    "Game trailers",
    "Onboarding",
    "Social shorts"
   ],
   "dur": 59.8,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/microgame.mp4",
   "frame": "../docs/frames/microgame.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/microgame/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/microgame/DEMO.md"
  },
  {
   "slug": "game-show",
   "num": "33",
   "en": "Game Show Flat",
   "cn": "综艺节奏扁平",
   "cat": "游戏",
   "cat_en": "Games",
   "film": "Rhythm of AI, 1997 → 2026",
   "line": "The history of AI as a rhythm game: models take the stage on the beat, and a report card closes the show.",
   "line_cn": "把 AI 发展史做成一局节奏游戏，模型踩着拍登场，最后发成绩单。",
   "uses": [
    "Tech timelines",
    "Year in review",
    "Variety shows"
   ],
   "dur": 148.8,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/game-show.mp4",
   "frame": "../docs/frames/game-show.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/game-show/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/game-show/DEMO.md"
  },
  {
   "slug": "pixel-8bit",
   "num": "72",
   "en": "8-bit Console Pixel",
   "cn": "8-bit 红白机像素",
   "cat": "游戏",
   "cat_en": "Games",
   "film": "Dusklight",
   "line": "Wick the lamplighter races the dusk through two scrolling stages, climbs a beacon tower, lights it through a moth swarm that overloads the sprite hardware, and sets a new high score.",
   "line_cn": "提灯人 Wick 在两段横版关卡里和黄昏赛跑，爬上灯塔，穿过让精灵硬件超载闪烁的飞蛾群点亮它，刷新最高分。",
   "uses": [
    "Game trailers and nostalgia pieces",
    "Countdowns, progress and score recaps",
    "Product feature lists told as stages"
   ],
   "dur": 54.4,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/pixel-8bit.mp4",
   "frame": "../docs/frames/pixel-8bit.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pixel-8bit/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/pixel-8bit/DEMO.md"
  },
  {
   "slug": "silent-film",
   "num": "34",
   "en": "1920s Silent Film",
   "cn": "1920s 默片",
   "cat": "电影与时代",
   "cat_en": "Cinema & Eras",
   "film": "The Runaway Loaf",
   "line": "A baker's boy chases a runaway loaf downhill, then breaks it in half for a hungry girl.",
   "line_cn": "面包店学徒追一个滚走的面包，最后掰成两半分给饿肚子的小女孩。",
   "uses": [
    "Comedy",
    "Retro brands",
    "Silent storytelling"
   ],
   "dur": 54.2,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/silent-film.mp4",
   "frame": "../docs/frames/silent-film.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/silent-film/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/silent-film/DEMO.md"
  },
  {
   "slug": "backrooms",
   "num": "36",
   "en": "Liminal Found Footage",
   "cn": "后室 / 新怪谈",
   "cat": "电影与时代",
   "cat_en": "Cinema & Eras",
   "film": "Night Shift Orientation",
   "line": "A new night-shift hire films their first night in an endless yellow office, following the rules on the wall.",
   "line_cn": "新夜班员工拍下入职第一晚：无尽的黄色办公空间，和墙上的员工守则。",
   "uses": [
    "Horror",
    "Mystery & ARG",
    "Game teasers"
   ],
   "dur": 59.7,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/backrooms.mp4",
   "frame": "../docs/frames/backrooms.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/backrooms/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/backrooms/DEMO.md"
  },
  {
   "slug": "super8",
   "num": "65",
   "en": "Super 8 Home Movie",
   "cn": "老胶片家庭录像",
   "cat": "电影与时代",
   "cat_en": "Cinema & Eras",
   "film": "Dad Was Here Too",
   "line": "A father films his family's 1976 seaside day without once appearing in it, until his daughter takes the camera and the reel burns out on him.",
   "line_cn": "爸爸把 1976 年一家人的海边一天拍成一卷胶片，自己从没入镜；直到女儿接过摄影机，胶片在他身上烧尽。",
   "uses": [
    "Family, travel & memory films",
    "Nostalgic brand stories",
    "Anniversaries & tributes"
   ],
   "dur": 56.7,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/super8.mp4",
   "frame": "../docs/frames/super8.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/super8/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/super8/DEMO.md"
  },
  {
   "slug": "brick-toy",
   "num": "37",
   "en": "Brick Toy",
   "cn": "积木玩具",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "Rocket from Spare Parts",
   "line": "A brick astronaut builds a rocket from spare parts and flies to a brick moon.",
   "line_cn": "积木宇航员用零件拼出火箭，飞向积木月亮。",
   "uses": [
    "Toys & kids",
    "Product builds",
    "Space"
   ],
   "dur": 54.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/brick-toy.mp4",
   "frame": "../docs/frames/brick-toy.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/brick-toy/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/brick-toy/DEMO.md"
  },
  {
   "slug": "paper-popup",
   "num": "41",
   "en": "Paper Pop-up Book",
   "cn": "纸片立体书",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "Pip's Paper Adventure",
   "line": "A pop-up book opens on a desk; a sprite named Pip adventures through paper worlds and jumps out into ours.",
   "line_cn": "立体书在书桌上打开，小精灵 Pip 在纸片世界冒险，最后跳出书外。",
   "uses": [
    "Children's books",
    "Game trailers",
    "Story films"
   ],
   "dur": 133.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/paper-popup.mp4",
   "frame": "../docs/frames/paper-popup.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/paper-popup/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/paper-popup/DEMO.md"
  },
  {
   "slug": "tilt-shift",
   "num": "42",
   "en": "Tilt-Shift Miniature",
   "cn": "移轴微缩",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "Toy Town Rush Hour",
   "line": "Morning rush hour in a town that looks like a model: traffic, trains and tiny people.",
   "line_cn": "玩具城的早高峰，一切都像模型。",
   "uses": [
    "City promos",
    "Real estate",
    "Transport"
   ],
   "dur": 38.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/tilt-shift.mp4",
   "frame": "../docs/frames/tilt-shift.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/tilt-shift/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/tilt-shift/DEMO.md"
  },
  {
   "slug": "lowpoly-island",
   "num": "43",
   "en": "Low-poly Isometric Island",
   "cn": "低多边形等距",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "The Island That Grew",
   "line": "An island and its village grow tile by tile from an empty sea, each tile a note, into a starry night.",
   "line_cn": "空海里一格格长出小岛和村庄，每放一块响一个音符，直到星空。",
   "uses": [
    "Game trailers",
    "World building",
    "Calm content"
   ],
   "dur": 53.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/lowpoly-island.mp4",
   "frame": "../docs/frames/lowpoly-island.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/lowpoly-island/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/lowpoly-island/DEMO.md"
  },
  {
   "slug": "glass-product",
   "num": "44",
   "en": "Glass Product Render",
   "cn": "玻璃质感产品",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "Aura — Hear the Light",
   "line": "Unboxing and close-ups of Aura, fictional glass earbuds, in strip-light sweeps and caustics.",
   "line_cn": "虚构玻璃耳机 Aura 的开箱与特写。",
   "uses": [
    "Product launches",
    "Consumer tech",
    "Beauty"
   ],
   "dur": 32.0,
   "added": false,
   "video": "https://github.com/lemomo-ai/lemo-opuscar/releases/download/films/glass-product.mp4",
   "frame": "../docs/frames/glass-product.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/glass-product/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/glass-product/DEMO.md"
  },
  {
   "slug": "claymation",
   "num": "55",
   "en": "Claymation / Stop-motion",
   "cn": "粘土定格动画",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "Proof",
   "line": "A worried lump of dough on a hand-built kitchen counter waits all night to rise; at dawn a giant clay finger pokes it, and it springs back.",
   "line_cn": "手捏小厨房里，一团忐忑的面团整夜不敢发酵；天亮时一根巨大的泥手指戳了它一下，它弹了回来。",
   "uses": [
    "Kids & family stories",
    "Food & craft",
    "Gentle explainers"
   ],
   "dur": 50.8,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/claymation.mp4",
   "frame": "../docs/frames/claymation.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/claymation/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/claymation/DEMO.md"
  },
  {
   "slug": "origami",
   "num": "61",
   "en": "Origami Fold",
   "cn": "折纸",
   "cat": "材质与 3D",
   "cat_en": "Materials & 3D",
   "film": "The Seventh Fold",
   "line": "A strip of paper is folded in half six times and the seventh will not close; the same strip is pleated, gathers into a wing, and opens with one pull.",
   "line_cn": "一条纸带对折六次，第七次再也折不动；换成风琴褶，同一条纸带收成一排折页，一拉就展开。",
   "uses": [
    "How-it-works explainers",
    "Product packaging and unboxing",
    "Instruction sheets and craft tutorials"
   ],
   "dur": 50,
   "added": true,
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/origami.mp4",
   "frame": "../docs/frames/origami.jpg",
   "style_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/origami/STYLE.md",
   "demo_md": "https://github.com/zhgarylu/claude-video/blob/main/styles/origami/DEMO.md"
  }
 ],
 "demos": [
  {
   "id": "claude-mods",
   "style": "dark-keynote",
   "dur": "0:31",
   "title": "Claude Code 的 mods",
   "title_en": "Claude Code mods",
   "layout": "split",
   "line": "暗色科技发布：讲者在左，右边一个原创界面窗口随口播装上面板、拦截命令、斜杠命令。",
   "line_en": "Dark Tech Keynote: the host on the left, an original UI window on the right that gains a pane, a command guard and slash commands as they speak.",
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/claude-mods.mp4",
   "poster": "../docs/talking-head/claude-mods.jpg",
   "style_en": "Dark Tech Keynote",
   "style_cn": "暗色科技发布"
  },
  {
   "id": "muse",
   "style": "iso-infographic",
   "dur": "0:33",
   "title": "Muse：把事情交给它",
   "title_en": "Muse: hand it your tasks",
   "layout": "pip",
   "line": "等距信息图：讲者缩成右上角小窗，镜头沿一块沙盘横移，四个工位讲清 Muse 的系统。",
   "line_en": "Isometric Infographic: the host shrinks to a corner window while the camera travels along a diorama of four stations.",
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/muse.mp4",
   "poster": "../docs/talking-head/muse.jpg",
   "style_en": "Isometric Infographic",
   "style_cn": "等距信息图"
  },
  {
   "id": "muse2",
   "style": "iso-infographic",
   "dur": "0:34",
   "title": "Muse：把事情交给它吗？",
   "title_en": "Muse: would you hand it your tasks?",
   "layout": "world",
   "line": "讲者本身就生成在等距小世界里演内容，视频当主画面，两侧用标签卡和引线补上名字、日期和来源。",
   "line_en": "The host is generated inside the isometric world and acts the story out; the video is the main picture, with callout cards adding names, dates and sources.",
   "video": "https://github.com/zhgarylu/claude-video/releases/download/films/muse2.mp4",
   "poster": "../docs/talking-head/muse2.jpg",
   "style_en": "Isometric Infographic",
   "style_cn": "等距信息图"
  }
 ],
 "counts": {
  "total": 61,
  "added": 18,
  "demos": 3
 }
};
