// generated by verify.py from the real interpreter: do not edit
export const V = {
 "buggy": [
  "16 -1",
  "38 -1",
  "7 -1"
 ],
 "fixed": [
  "16 4",
  "38 6",
  "7 -1"
 ],
 "py": "3.12.4",
 "srcBuggy": "def binary_search(items, target):\n    lo, hi = 0, len(items) - 1\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if items[mid] == target:\n            return mid\n        if items[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\n\nnums = [2, 5, 8, 12, 16, 23, 38]\nfor target in (16, 38, 7):\n    print(target, binary_search(nums, target))\n",
 "srcFixed": "def binary_search(items, target):\n    lo, hi = 0, len(items) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if items[mid] == target:\n            return mid\n        if items[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\n\nnums = [2, 5, 8, 12, 16, 23, 38]\nfor target in (16, 38, 7):\n    print(target, binary_search(nums, target))\n",
 "traceBuggy": [
  {
   "line": 2
  },
  {
   "line": 3,
   "lo": 0,
   "hi": 6
  },
  {
   "line": 4,
   "lo": 0,
   "hi": 6
  },
  {
   "line": 5,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 7,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 8,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 3,
   "lo": 4,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 4,
   "lo": 4,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 5,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 7,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 10,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 3,
   "lo": 4,
   "hi": 4,
   "mid": 5
  },
  {
   "line": 11,
   "lo": 4,
   "hi": 4,
   "mid": 5
  },
  {
   "line": -1,
   "ret": -1
  }
 ],
 "traceFixed": [
  {
   "line": 2
  },
  {
   "line": 3,
   "lo": 0,
   "hi": 6
  },
  {
   "line": 4,
   "lo": 0,
   "hi": 6
  },
  {
   "line": 5,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 7,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 8,
   "lo": 0,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 3,
   "lo": 4,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 4,
   "lo": 4,
   "hi": 6,
   "mid": 3
  },
  {
   "line": 5,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 7,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 10,
   "lo": 4,
   "hi": 6,
   "mid": 5
  },
  {
   "line": 3,
   "lo": 4,
   "hi": 4,
   "mid": 5
  },
  {
   "line": 4,
   "lo": 4,
   "hi": 4,
   "mid": 5
  },
  {
   "line": 5,
   "lo": 4,
   "hi": 4,
   "mid": 4
  },
  {
   "line": 6,
   "lo": 4,
   "hi": 4,
   "mid": 4
  },
  {
   "line": -1,
   "ret": 4
  }
 ]
};
