"""Runs the two files shown in the film with the real Python interpreter and writes verified.js:
the true stdout of each, and the true line-by-line trace of binary_search(nums, 16) (via sys.settrace).
The film imports verified.js, so every number on screen is something the interpreter printed."""
import subprocess, sys, os, json, runpy
HERE = os.path.dirname(os.path.abspath(__file__)); C = os.path.join(HERE, 'code')
def run(name): return subprocess.run([sys.executable, os.path.join(C, name)], capture_output=True, text=True, check=True).stdout.splitlines()
def trace(name, target):
    ev = []
    def tracer(frame, event, arg):
        if frame.f_code.co_name != 'binary_search' or frame.f_locals.get('target') != target: return tracer if event == 'call' and frame.f_code.co_name == '<module>' else None
        def local(fr, ev_, a):
            if ev_ == 'line': ev.append({'line': fr.f_lineno, **{k: v for k, v in fr.f_locals.items() if k in ('lo', 'hi', 'mid')}})
            if ev_ == 'return': ev.append({'line': -1, 'ret': a})
            return local
        return local
    sys.settrace(tracer)
    try: runpy.run_path(os.path.join(C, name), run_name='traced')
    finally: sys.settrace(None)
    return ev
out = {'buggy': run('search_buggy.py'), 'fixed': run('search.py'), 'py': sys.version.split()[0]}
out['srcBuggy'] = open(os.path.join(C, 'search_buggy.py')).read(); out['srcFixed'] = open(os.path.join(C, 'search.py')).read()
out['traceBuggy'] = trace('search_buggy.py', 16); out['traceFixed'] = trace('search.py', 16)
# the choreography of the film assumes exactly this behaviour: fail loudly if the code ever changes
assert out['buggy'] == ['16 -1', '38 -1', '7 -1'], out['buggy']
assert out['fixed'] == ['16 4', '38 6', '7 -1'], out['fixed']
mids = [(e['lo'], e['hi'], e['mid']) for e in out['traceFixed'] if e['line'] == 5]
assert mids == [(0, 6, 3), (4, 6, 5), (4, 4, 4)], mids
assert len([e for e in out['traceBuggy'] if e['line'] == 5]) == 2, 'buggy loop should stop after two turns'
assert out['traceBuggy'][-1] == {'line': -1, 'ret': -1}
open(os.path.join(HERE, 'verified.js'), 'w').write('// generated by verify.py from the real interpreter: do not edit\nexport const V = ' + json.dumps(out, indent=1) + ';\n')
print('verified', out['buggy'], out['fixed'], mids, 'python', out['py'])
